import {GetServerSideProps} from 'next';
import Head from 'next/head';
import {useAppSelector} from '~/store';
// import Image from 'next/image';
// import {Inter} from '@next/font/google';
// import styles from '@/styles/Home.module.css';

// const inter = Inter({subsets: ['latin']});

interface IProps {
    time: string;
}

export default function Home(props: IProps) {
    const storeTime = useAppSelector(n => n.app.time);
    console.log(storeTime);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>This is Page Index - {storeTime}</div>
                <div>{props.time}</div>
            </main>
        </>
    );
}

export const getServerSideProps: GetServerSideProps<IProps> = async ctx => {
    const time = new Date().toLocaleString();
    return {
        props: {time}
    };
};
